***label the indicators, note: the labels are truncated and are incomplete. 		
		
label var c_anc  "15-49y had 4+ ANC visits in last pregnancy in L2Y (1/0)"
label var c_anc_any  "15-49y had any ANC visits in last pregnancy in L2Y (1/0)"
label var c_anc_bp  "15-49y had blood pressure measured during last pregnancy in L2Y (1/0)"
label var c_anc_bp_q  "15-49y among ANC users had blood pressure measured during last pregna"
label var c_anc_bs  "15-49y had blood sample taken during last pregnancy in L2Y (1/0)"
label var c_anc_bs_q  "15-49y among ANC users had blood sample taken during last pregnancy i"
label var c_anc_ear  "15-49y had first ANC visit in first trimester of last pregnancy in L2"
label var c_anc_ear_q  "15-49y among ANC users had first ANC visit in first trimester of last"
label var c_anc_eff  "15-49y had effective ANC visits (4+ visits, skilled provider, blood p"
label var c_anc_eff_q  "15-49y among ANC users had effective ANC visits (4+ visits, skilled p"
label var c_anc_eff2  "15-49y had effective ANC2 (4+ antenatal care visits, any skilled prov"
label var c_anc_eff2_q  "15-49y among ANC users had effective ANC2 (4+ antenatal care visits,"
label var c_anc_eff3  "15-49y had effective ANC3 (4+ antenatal care visits, any skilled prov"
label var c_anc_eff3_q  "15-49y had effective ANC3 (4+ antenatal care visits, any skilled prov"
label var c_anc_ir  "15-49y took iron supplements during last pregnancy in L2Y (1/0)"
label var c_anc_ir_q  "15-49y among ANC users took iron supplements during last pregnancy in"
label var c_anc_ski  "15-49y had ANC visit with a skilled provider in last pregnancy in L2Y"
label var c_anc_ski_q  "15-49y among ANC users had ANC visit with a skilled provider in last"
label var c_anc_tet  "15-49y woman vaccinated against tetanus for last pregnancy in L2Y (1/"
label var c_anc_tet_q  "15-49y among ANC users woman vaccinated against tetanus for last preg"
label var c_anc_ur  "15-49y had urine sample taken during last pregnancy in L2Y (1/0)"
label var c_anc_ur_q  "15-49y among ANC users had urine sample taken during last pregnancy i"
label var c_anc_pub "15-49y among ANC users had antenatal care in public facilities"
label var c_anc_hosp "15-49y among ANC users had antenatal care in hospital setting"
label var c_caesarean  "15-49y had caesarean for last birth in L2Y (1/0)"
label var c_earlybreast  "15-49y child breastfed within 1 hour of birth in last pregnancy in L2"
label var c_facdel  "15-49y child born in formal health facility in last pregnancy in L2Y"
label var c_hospdel  "15-49y child born in hospital in last pregnancy in L2Y (1/0)"
label var c_sba  "15-49y had SBA for last birth in L2Y (1/0)"
label var c_sba_eff1  "15-49y SBA, facility, immediate breastfeeding"
label var c_sba_eff1_q  "Among those with SBA, 15-49y SBA, facility, immediate breastfeeding"
label var c_sba_eff2  "15-49y SBA, facility, immediate breastfeeding, skin2skin"
label var c_sba_eff2_q  "Among those with SBA, 15-49y SBA, facility, immediate breastfeeding,"
label var c_sba_q  "15-49y child placed on mother's bare skin and breastfeeding initiated"
label var c_skin2skin  "15-49y child placed on mother's bare skin immediately after birth in"
label var c_pnc_any  "15-49y child OR woman received any postnatal care in first six weeks"
label var c_pnc_eff  "15-49y child AND women received any postnatal care in first 24 hours"
label var c_pnc_eff_q  "Among PNC users 15-49y child AND women received any postnatal care in"
label var c_pnc_eff2  "15-49y child AND women received any postnatal care in first 24 hours"
label var c_pnc_eff2_q  "Among PNC users 15-49y child AND women received any postnatal care in"
label var w_CPR  "15-49y, married/in union currently uses modern contraceptives (1/0)"
label var w_unmet_fp  "15-49y married or in union with unmet need for family planning (1/0)"
label var w_need_fp  "15-49 married or in union women"
label var w_metany_fp  "15-49y married or in union with need for family planning using any contraceptives (1/0)"
label var w_metmod_fp  "15-49y married or in union with need for family planning using modern contraceptives (1/0)"
label var w_metany_fp_q  "15-49y married or in union using modern contraceptives among those with need for family planning who use any contraceptives (1/0)"
label var w_condom_conc  "18-49y, 2+ sex partners in L12M used condom in last sex (1/0)"
label var w_bmi_1549  "15-49y woman's BMI"
label var w_height_1549  "15-49y woman's height in meters"
label var w_obese_1549  "15-49y woman's BMI>30 (1/0)"
label var w_overweight_1549  "15-49y woman's BMI>25 (1/0)"
label var c_bcg  "15-23M had BCG vaccination (1/0)"
label var c_dpt1  "15-23M had DPT1 or Pentavalent 1 vaccination (1/0)"
label var c_dpt2  "15-23M had DPT2 or Pentavalent 2 vaccination (1/0)"
label var c_dpt3  "15-23M had DPT3 or Pentavalent 3 vaccination (1/0)"
label var c_fullimm  "15-23M had BCG, polio 1-3, DTP/Penta1-3 & measles/MMR (1/0)"
label var c_measles  "15-23M had measles/MMR vaccination (1/0)"
label var c_polio1  "15-23M had polio1/OPV1 vaccination (1/0)"
label var c_polio2  "15-23M had polio2/OPV2 vaccination (1/0)"
label var c_polio3  "15-23M had polio3/OPV3 vaccination (1/0)"
label var c_ari  "0-4y with ARI in L2W (1/0)"
label var c_diarrhea   "0-4y with diarrhea in L2W (1/0)"
label var c_diarrhea_hmf  "0-4y with diarrhea in L2W got government-recommended home-made solution (1/0)"
label var c_diarrhea_medfor  "0-4y with diarrhea in L2W got formal medicine other than ORS"
label var c_diarrhea_mof  "0-4y with diarrhea in L2W given more to drink"
label var c_diarrhea_pro  "0-4y with diarrhea in L2W seen by formal provider"
label var c_diarrheaact  "0-4y with diarrhea in L2W seen by formal provider or given any form of treatment"
label var c_diarrheaact_q  "0-4y with diarrhea in L2W seen by formal provider or given any form of treatment if receiving ORS"
label var c_fever  "0-4y with fever in L2W"
label var c_fevertreat  "0-4y with fever in L2W seen by formal healthcare provider"
label var c_illness  "0-4 with diarrhea, rapid breathing and/or fever in L2W"
label var c_illtreat  "0-4 with diarrhea, rapid breathing and/or fever in L2W seen by formal provider"
label var c_sevdiarrhea  "0-4y with severe diarrhea"
label var c_sevdiarrheatreat  "0-4y with severe diarrhea in L2W seen by fromal healthcare provider (1/0)"
label var c_sevdiarrheatreat_q  "0-4y with severe diarrhea in L2W seen by fromal healthcare provider who r"
label var c_treatARI  "0-4y with ARI in L2W seen by formal provider (1/0)"
label var c_treatdiarrhea  "0-4y with diarrhea in L2W got ORS (1/0)"
label var c_diarrhea_med  "0-4y with diarreha received any meds other than ORS"
label var c_underweight  "0-4y WfA <-2 std.dev. from median (WHO) (1/0)"
label var c_stunted  "0-4y HfA <-2 std.dev. from median (WHO) (1/0)"
label var c_wasted  "0-4y WfH <-2 std.dev. from median (WHO) (1/0)"
label var c_underweight_sev  "0-4y WfA <-3 std.dev. from median (WHO) (1/0)"
label var c_stunted_sev  "0-4y HfA <-3 std.dev. from median (WHO) (1/0)"
label var c_wasted_sev  "0-4y WfH <-3 std.dev. from median (WHO) (1/0)"
*label var hc70  "ht/a standard deviations (according to who)hc70"
*label var hc71  "wt/a standard deviations (according to who)hc71"
label var ant_sampleweight  "0-4y anthro sample weight"
label var mor_ade  "Child age at death in months"
label var mor_afl  "Child age at death imputation flag"
label var mor_ali  "Child still alive (1/0)"
label var mor_dob  "Child date of birth (cmc)"
label var mor_wln  "Woman line number in HH to match child with mother (original)"
label var c_ITN  "0-4y slept under an ITN the night before the survey (1/0)"
label var c_mateduc  "Level of education of child's mother"
label var a_hiv  "15-49y household member tested positive for HIV1 or HIV2 (1/0)"
label var a_hiv_sampleweight  "Sample weight for hiv prevalence estimates"
label var a_diab_treat  "18y+ being treated for raised blood glucose or diabetes (1/0)"
label var a_inpatient_1y  "18y+ household member hospitalized in last 12 months (1/0)"
label var a_bp_treat  "18y + being treated for high blood pressure (1/0)"
label var a_bp_sys  "18y+ systolic blood pressure (mmHg) in adult population"
label var a_bp_dial  "18y+ diastolic blood pressure (mmHg) in adult population"
label var a_hi_bp140_or_on_med  "18y+ with high blood pressure or on treatment for high blood pressure (1/0)"
label var a_bp_meas  "18y+ having their blood pressure measured by health professional in the last year (1/0)"
label var w_sampleweight  "Household member sampling weight"
label var hm_live  "Living and in HH (1/0)"
label var hm_male  "Male (1/0)"
label var hm_age_yrs  "Age in years"
label var hm_age_mon  "Age in months (children only)"
label var hm_headrel  "Relationship with HH head"
label var hm_stay  "Stayed in the HH the night before the survey (1/0)"
label var hm_dob  "date of birth (cmc)"
label var hm_doi  "date of interview (cmc)"
label var ln  "Original line number of household member"
label var hh_id  "ID (generated)"
label var hh_headed  "Head's highest educational attainment"
label var hh_region_num  "Region of residence numerical (v024)"
label var hh_region_lab  "Region of residence label (v024)"
label var hh_size  "# of members"
label var hh_urban  "Resides in urban area (1/0)"
label var hh_sampleweight  "Sample weight (v005/1000000)"
cap label var hh_wealth_quintile  "Wealth quintile"
cap label var hh_wealthscore  "Wealth index score"
/* label var gl_adm0_code  "GAUL country code"
label var gl_adm1_code  "GAUL level one code" */
label var hv001  "Sampling cluster number (original)"
label var hv002  "Household number (original)"
label var hvidx  "Respondent's line number in household roster (original)"
label var w_papsmear  "Women received a pap smear (1/0)"
label var w_mammogram  "Women received a mammogram (1/0)"
label var w_papsmear_ref  "Women received a pap smear, reference period (1/0)"
label var w_mammogram_ref  "Women received a mammogram, refrence period (1/0)"
label var w_papsmear_age  "Women received a pap smear, age group (1/0)"
label var w_mammogram_age  "Women received a mammogram, age group (1/0)"
label var survey  "Survey name"
label var year  "Year survey conducted (if multiple, put in first)"
label var country  "WB country name"
label var iso3c  "iso3c country code"
label var iso2c  "iso2 country code"

* DW NOV 2021
		label var w_married "Marital Status"
		label var c_vaczero "Child: Not Received Any Vaccination"
		label var c_stu_was "Child: Child under five both stunted and wasted"
		label var c_stu_was_sev "Child: Child under five both severely stunted and severely wasted"
		label var c_motherln "The line number of the mother for each kid"
		label var c_hfa "Child: 0-4y HfA std.dev. from median (WHO), hc70"
		label var c_wfa "Child: 0-4y WfA std.dev. from median (WHO), hc71"
		label var c_wfh "Child: 0-4y WfH std.dev. from median (WHO), hc72"	
		label var hm_birthorder "Birth Order"
		label var c_magebrt "Age of the mother at the child’s birth, based on b2, v007 and v012"
		cap label var hh_religion "Head of Household Religion"
		label var hh_watersource "Water Source"
		label var hh_toilet "Toilet type"
* DW Apr 2021
		label var c_mateduclvl_raw "Level of education of child's mother - original variable"
		label var c_maleduclvl_raw "Level of education of husband/partner - original variable"
		label var hh_headage_raw "Age of head of household - original"
		label var hh_headsex_raw "Sex of head of household - original"
		label var hh_headedu_comp "Education of head of household - computed"
		
foreach v of varlist * {
    local x : variable label `v'
    if "`x'" == "" drop `v'
}
